size	:100;
height	:10;
element	:0;
empty	: ;
                                      0000                                                              
                                      0000                                                             
                                      0000                                                             
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                    
                                                                                                    
end;
